---
- hosts: localhost
  connection: local
  become: true # sudo


  tasks:
  - name: install packages
    package: 
      name: 
        - git
        - base-devel
        - networkmanager
        - archlinux-appstream-data
        - flatpak
        - packagekit-qt5
        - packagekit-qt6
        - qt5-base
        - qt6-base
        - qt5-tools
        - qt6-tools
        - libusb
        - mbedtls
        - mbedtls2
        - fwupd
        - a52dec
        - faac
        - faad2
        - flac
        - jasper
        - lame
        - libdca
        - libdv
        - libmad
        - libmpeg2
        - libtheora
        - libvorbis
        - libxv
        - libva-utils
        - vdpauinfo
        - ffmpeg
        - opus
        - wavpack
        - x264
        - x265
        - xvidcore
        - adobe-source-han-sans-otc-fonts
        - adobe-source-han-serif-otc-fonts
        - noto-fonts
        - noto-fonts-cjk noto-fonts-emoji
        - ttf-liberation
        - wqy-zenhei
        - lib32-systemd
        - nvidia
        - nvidia-utils
        - lib32-nvidia-utils
        - nvidia-settings
        - vulkan-icd-loader
        - lib32-vulkan-icd-loader
        - firefox
        - nano
        - htop
        - curl
        - wget
        - bluez
        - bluez-utils
        - code
        - rustup
        - jdk-openjdk
        - python
        - python-pip
        - gcc
        - maven
        - docker
        - docker-compose
        - fish
        - nextcloud-client
    register: package_install_result


  - name: Handle errors if package installation fails
    fail:
      msg: "Package installation failed"
    when: package_install_result.failed

  - name: Add Flathub remote
    command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  - name: Install Flatpak applications
    flatpak:
      name: "{{ item }}"
      state: present
      remote: flathub
    loop:
      - ca.desrt.dconf-editor
      - com.bitwarden.desktop
      - com.github.flxzt.rnote
      - com.github.tchx84.Flatseal
      - com.github.wwmm.easyeffects
      - com.mattjakeman.ExtensionManager
      - com.spotify.Client
      - io.github.Foldex.AdwSteamGtk
      - io.github.dyegoaurelio.simple-wireplumber-gui
      - io.github.java_decompiler.jd-gui
      - org.gnome.Boxes
      - org.gnome.Boxes.Extension.OsinfoDb
      - org.gnome.Builder
      - org.gnome.Geary
      - org.gnome.gitlab.cheywood.Iotas
      - org.gnome.seahorse.Application
      - org.gtk.Gtk3theme.adw-gtk3
      - org.gtk.Gtk3theme.adw-gtk3-dark	
      - org.pipewire.Helvum
      - re.sonny.Workbench
      - io.gitlab.news_flash.NewsFlash
      - org.openrgb.OpenRGB

  - name: copy Nextcloud - sync-exclude.lst
    copy:
      src:  files/sync-exclude.lst
      dest: /home/tim/.sync-exclude.lst
      owner: tim
      group: tim

  - name: copy wireplumber config
    copy:
      src:  files/60-alsa-config.lua
      dest: ~/.config/wireplumber/main.lua.d/60-alsa-config.lua
      owner: tim
      group: tim
