---
- name: Pacman App Installation Playbook
  hosts: all
  gather_facts: yes
  ignore_unreachable: true

  tasks:
    - name: install packages
      become: true
      package:
        name:
          - adobe-source-han-sans-otc-fonts
          - adobe-source-han-serif-otc-fonts
          - a52dec
          - archlinux-appstream-data
          - atuin
          - base-devel
          - bluez
          - bluez-utils
          - cliphist
          - composer
          - curl
          - discord
          - docker
          - docker-compose
          - faac
          - faad2
          - fd
          - ffmpeg
          - firefox
          - fish
          - flatpak
          - flac
          - fwupd
          - gcc
          - git
          - git-lfs
          - htop
          - hyprland
          - intellij-idea-community-edition
          - jasper
          - jdk-openjdk
          - kitty
          - lib32-nvidia-utils
          - lib32-systemd
          - lib32-vulkan-icd-loader
          - libdca
          - libdv
          - libmad
          - libmpeg2
          - libtheora
          - libusb
          - libva-utils
          - libvorbis
          - libxv
          - lua
          - luarocks
          - lame
          - man-db
          - man-pages
          - mbedtls
          - mbedtls2
          - maven
          - nano
          - neofetch
          - neovim
          - networkmanager
          - nodejs
          - noto-fonts
          - noto-fonts-cjk
          - noto-fonts-emoji
          - npm
          - nwg-look
          - nvidia-open-dkms
          - nvidia-settings
          - nvidia-utils
          - otf-font-awesome
          - opus
          - packagekit-qt5
          - packagekit-qt6
          - pamixer
          - pacman-contrib
          - perl
          - php
          - playerctl
          - polkit-gnome
          - pycharm-community-edition
          - python
          - python-pip
          - python-pynvim
          - qt5-base
          - qt5-tools
          - qt5-wayland
          - qt6ct
          - qt6-base
          - qt6-tools
          - qt6-wayland
          - ripgrep
          - rnote
          - rsync
          - ruby
          - rubygems
          - rustup
          - steam
          - syncthing
          - ttf-jetbrains-mono
          - ttf-liberation
          - tree-sitter
          - tree-sitter-cli
          - vdpauinfo
          - vulkan-icd-loader
          - wofi
          - wavpack
          - wget
          - wl-clipboard
          - wqy-zenhei
          - x264
          - x265
          - xclip
          - xdg-desktop-portal-hyprland
          - xvidcore
          - waybar
          - wl-clipboard
      register: package_install_result